# Generated by Django 5.2.3 on 2025-06-21 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Drużyna',
                'verbose_name_plural': 'Drużyny',
            },
        ),
        migrations.CreateModel(
            name='Turniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('liga', 'Liga'), ('puchar', 'Puchar')], max_length=10)),
                ('liczba_druzyn', models.PositiveIntegerField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_rozpoczecia', models.DateField(blank=True, null=True)),
                ('data_zakonczenia', models.DateField(blank=True, null=True)),
                ('miejsce', models.CharField(blank=True, max_length=100, null=True)),
                ('wlasciciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnieje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turniej',
                'verbose_name_plural': 'Turnieje',
            },
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('godzina', models.TimeField(blank=True, null=True)),
                ('miejsce', models.CharField(blank=True, max_length=100)),
                ('wynik_a', models.IntegerField(blank=True, null=True)),
                ('wynik_b', models.IntegerField(blank=True, null=True)),
                ('runda', models.CharField(blank=True, max_length=50)),
                ('druzyna_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecz_a', to='pilka_nozna.druzyna')),
                ('druzyna_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecz_b', to='pilka_nozna.druzyna')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilka_nozna.turniej')),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'ordering': ['data', 'godzina', 'id'],
            },
        ),
        migrations.AddField(
            model_name='druzyna',
            name='turniej',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyny', to='pilka_nozna.turniej'),
        ),
        migrations.AlterUniqueTogether(
            name='druzyna',
            unique_together={('nazwa', 'turniej')},
        ),
    ]
